### ISSUE TITLE
Changing approximation factor of uniformity

### ISSUE THREAD

**Issue by allrtaken** [meelgroup/unigen#5]
Hi,

I wanted to confirm whether the parameter epsilon in the command-line options is the approximation factor of uniformity of the samples (as mentioned in the Readme). I am asking this since I also saw a parameter delta in command-line help options which was a bit confusing.

Thanks!

**Comment by msoos** [comment]
@kuldeepmeel  Please respond. The fact that this is not clear to someone who is clearly extremely knowledgeable means to me that people without a PhD *in this specific field* will be confused -- we want this to be used by people who have good mathematical understanding, without necessarily a PhD in this specific area, right? Can we _please_ for the love of all that is holy, use a language that it more amenable to normal human beings?

I understand that the paper (that, let's be honest, few will read, even if many will cite) uses these specific parameter names. But the implementation  doesn't need to conform to it in the use of parameter names, necessarily, right? And even if we somehow, by the decision of the almighty, *must* use such wonky naming -- can we _please_ add some text to the option's `--help` so it's understandable by us, humans? :smile: 

Thanks in advance,

Mate

**Comment by msoos** [comment]
Hi,

So this has since been fixed, thanks for reporting. I got so confused at one point, I fixed it out of frustration with myself. I have tried explaining it in the `--help`. I know this is late, but better late than never. Also the username @allrtaken someone got associated in my mind with someone trying to mess with me, due to the weird nature of the username, so that's my fault, sorry. Weird username, though, but always very cool suggestions. I'll try to rearrange my brain to have this username not have unnecessary connotations. Sorry!
